const seedProducts = [
	{id:'p1',type:'cake',name:'Strawberry Cloud',description:'Vanilla sponge, fresh strawberries, and a soft whipped finish.',price:48,salePrice:39, sale:true,available:true,featured:true,isNew:false,image:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=700&q=82'},
	{id:'p2',type:'cake',name:'Caramel Fig',description:'Brown sugar layers, salted caramel, and a little fig confit.',price:56,salePrice:null,sale:false,available:true,featured:true,isNew:true,image:'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=700&q=82'},
	{id:'p3',type:'cake',name:'Citrus Olive Oil',description:'Bright lemon, orange zest, and a tender olive oil crumb.',price:42,salePrice:null,sale:false,available:true,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=700&q=82'},
	{id:'p4',type:'cupcake',name:'Rose Vanilla',description:'Silky vanilla buttercream finished with a rose petal.',price:5.5,salePrice:4.5,sale:true,available:true,featured:true,isNew:true,image:'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=700&q=82'},
	{id:'p5',type:'cupcake',name:'Dark Chocolate',description:'Deep cocoa cake with a glossy chocolate swirl.',price:5,salePrice:null,sale:false,available:true,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=700&q=82'},
	{id:'p6',type:'cupcake',name:'Lemon Meringue',description:'Lemon curd centre, vanilla crumb, and toasted meringue.',price:5.5,salePrice:null,sale:false,available:false,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=700&q=82'}
];
const store = { products: JSON.parse(localStorage.getItem('khloeProducts') || 'null') || seedProducts, orders: JSON.parse(localStorage.getItem('khloeOrders') || '[]'), basket: [] };
const money = value => 'K' + Number(value).toFixed(2);
const save = () => { localStorage.setItem('khloeProducts', JSON.stringify(store.products)); localStorage.setItem('khloeOrders', JSON.stringify(store.orders)); };
const el = id => document.getElementById(id);
const show = id => el(id).classList.add('open');
const hide = id => el(id).classList.remove('open');
function toast(message) { const node = el('toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
function card(product) { const onSale = product.sale && product.salePrice && product.salePrice < product.price; const discount = onSale ? Math.round((1 - product.salePrice / product.price) * 100) : 0; return `<article class="product-card"><div class="product-image"><img src="${product.image || 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=82'}" alt="${product.name}">${onSale ? `<span class="badge">Sale -${discount}%</span>` : product.isNew ? '<span class="badge new">New</span>' : ''}</div><div class="product-body"><div class="product-top"><div class="product-title">${product.name}</div><span class="availability ${product.available ? '' : 'off'}">${product.available ? 'Available' : 'Sold out'}</span></div><p class="product-desc">${product.description}</p><div class="product-footer"><div class="price">${onSale ? `<span class="old-price">${money(product.price)}</span>${money(product.salePrice)}` : money(product.price)}</div><button class="mini-btn" data-add="${product.id}" ${product.available ? '' : 'disabled'}>${product.available ? 'Order now' : 'Unavailable'}</button></div></div></article>`; }
function renderGrid(id, products) { el(id).innerHTML = products.length ? products.map(card).join('') : '<div class="empty">No treats found here right now. Check back soon!</div>'; }
function renderAll() { const cakes = store.products.filter(p => p.type === 'cake'); const cupcakes = store.products.filter(p => p.type === 'cupcake'); renderGrid('featuredGrid', store.products.filter(p => p.featured).slice(0,3)); renderGrid('cakesGrid', filtered(cakes, document.querySelector('#cakes [data-search]'), document.querySelector('#cakes [data-filter]'))); renderGrid('cupcakesGrid', filtered(cupcakes, document.querySelector('#cupcakes [data-search]'), document.querySelector('#cupcakes [data-filter]'))); renderGrid('promotionsGrid', store.products.filter(p => p.sale && p.salePrice && p.salePrice < p.price)); el('cartCount').textContent = store.basket.reduce((sum,item) => sum + item.quantity, 0); }
function filtered(products, search, filter) { const term = search ? search.value.toLowerCase() : ''; return products.filter(p => (!term || `${p.name} ${p.description}`.toLowerCase().includes(term)) && (filter.value === 'all' || (filter.value === 'sale' ? p.sale : p.available))); }
function renderBasket() { if (!store.basket.length) { el('basketItems').innerHTML = '<div class="empty">Your basket is waiting for something sweet.</div>'; return; } el('basketItems').innerHTML = store.basket.map(item => `<div style="display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--line);font-size:13px"><span>${item.quantity} &times; ${item.product.name}</span><strong>${money(item.quantity * (item.product.sale && item.product.salePrice < item.product.price ? item.product.salePrice : item.product.price))}</strong></div>`).join(''); }
function addToBasket(id) { const product = store.products.find(p => p.id === id); const existing = store.basket.find(item => item.product.id === id); if (existing) existing.quantity++; else store.basket.push({product,quantity:1}); renderBasket(); show('orderModal'); }
function renderAdmin(view = 'products') { const area = el('adminContent'); if (view === 'orders') { const orders = [...store.orders].reverse(); el('orderCountLabel').textContent = orders.length ? `(${orders.length})` : ''; el('newOrderBadge').textContent = store.orders.filter(o => o.status === 'New').length ? '  • NEW ORDER' : ''; area.innerHTML = orders.length ? orders.map(order => `<div class="order-card"><div class="order-head"><strong>${order.number} &middot; ${order.customer}</strong><strong>${money(order.total)}</strong></div><div class="order-meta">${order.contact} &middot; ${new Date(order.createdAt).toLocaleString()}${order.instructions ? ` &middot; Note: ${order.instructions}` : ''}</div><div class="order-items">${order.items.map(item => `${item.quantity} &times; ${item.product.name} (${money(item.price)})`).join('<br>')}</div><select data-order-status="${order.id}">${['New','Confirmed','Preparing','Ready','Completed','Cancelled'].map(status => `<option ${status === order.status ? 'selected' : ''}>${status}</option>`).join('')}</select></div>`).join('') : '<div class="empty">No orders yet. New orders will appear here.</div>'; } else { area.innerHTML = `<div style="color:var(--muted);font-size:12px;margin-bottom:6px">${store.products.length} products in your public menu</div>` + store.products.map(p => `<div class="admin-product"><img src="${p.image}" alt=""><div class="admin-product-info"><strong>${p.name}</strong><small>${p.type} &middot; ${p.sale ? 'On sale' : 'Regular price'} &middot; ${p.available ? 'Available' : 'Unavailable'}</small></div><strong>${money(p.sale && p.salePrice < p.price ? p.salePrice : p.price)}</strong><div class="admin-product-actions"><button data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Delete</button></div></div>`).join(''); } }
function readImageFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function editProduct(product) { el('productModalTitle').textContent = product ? 'Edit product' : 'Add product'; el('productId').value = product?.id || ''; el('productType').value = product?.type || 'cake'; el('productName').value = product?.name || ''; el('productDescription').value = product?.description || ''; el('productPrice').value = product?.price || ''; el('productSalePrice').value = product?.salePrice || ''; el('productImage').value = ''; el('productImageCurrent').value = product?.image || ''; el('productSale').checked = !!product?.sale; el('productAvailable').checked = product ? product.available : true; el('productFeatured').checked = !!product?.featured; el('productNew').checked = !!product?.isNew; show('productModal'); }
document.addEventListener('click', event => { const add = event.target.closest('[data-add]'); if (add) addToBasket(add.dataset.add); const edit = event.target.closest('[data-edit]'); if (edit) editProduct(store.products.find(p => p.id === edit.dataset.edit)); const remove = event.target.closest('[data-delete]'); if (remove && confirm('Remove this product from the menu?')) { store.products = store.products.filter(p => p.id !== remove.dataset.delete); save(); renderAll(); renderAdmin(); toast('Product removed'); } });
document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => hide(button.dataset.close)));
document.querySelectorAll('[data-search],[data-filter]').forEach(control => control.addEventListener('input', renderAll));
el('cartBtn').addEventListener('click', () => { renderBasket(); show('orderModal'); });
el('menuBtn').addEventListener('click', () => el('navLinks').classList.toggle('open'));
const openLogin = () => show('loginModal'); el('adminBtn').addEventListener('click', openLogin); el('footerAdmin').addEventListener('click', openLogin);
el('loginForm').addEventListener('submit', event => { event.preventDefault(); if (el('adminPassword').value === 'khloe-admin') { hide('loginModal'); renderAdmin(); show('adminModal'); el('adminPassword').value = ''; } else toast('That password did not match.'); });
el('addProductBtn').addEventListener('click', () => editProduct()); el('ordersTabBtn').addEventListener('click', () => renderAdmin('orders'));
el('productForm').addEventListener('submit', async event => { event.preventDefault(); const imageFile = el('productImage').files[0]; const image = imageFile ? await readImageFile(imageFile) : (el('productImageCurrent').value || 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=82'); const id = el('productId').value || `p${Date.now()}`; const product = {id,type:el('productType').value,name:el('productName').value.trim(),description:el('productDescription').value.trim(),price:Number(el('productPrice').value),salePrice:el('productSalePrice').value ? Number(el('productSalePrice').value) : null,sale:el('productSale').checked,available:el('productAvailable').checked,featured:el('productFeatured').checked,isNew:el('productNew').checked,image}; const index = store.products.findIndex(p => p.id === id); if (index >= 0) store.products[index] = product; else store.products.push(product); save(); hide('productModal'); renderAll(); renderAdmin(); toast('Menu updated'); });
el('orderForm').addEventListener('submit', event => { event.preventDefault(); if (!store.basket.length) return toast('Add a treat before placing your order.'); const items = store.basket.map(item => ({product:item.product,quantity:item.quantity,price:item.product.sale && item.product.salePrice < item.product.price ? item.product.salePrice : item.product.price})); const total = items.reduce((sum,item) => sum + item.quantity * item.price, 0); store.orders.push({id:`o${Date.now()}`,number:`KST-${String(store.orders.length + 1).padStart(4,'0')}`,customer:el('customerName').value,contact:el('customerContact').value,instructions:el('instructions').value,items,total,createdAt:new Date().toISOString(),status:'New'}); store.basket = []; save(); hide('orderModal'); el('orderForm').reset(); renderAll(); toast('Order received. We will be in touch soon!'); });
el('customOrderForm').addEventListener('submit', event => { event.preventDefault(); const budget = el('customBudget').value ? Number(el('customBudget').value) : 0; const details = [`Needed by: ${el('customDate').value}`, `Request type: ${el('customType').value}`, `Servings or quantity: ${el('customServings').value}`, `Flavours and fillings: ${el('customFlavours').value}`, `Colours, theme, and design: ${el('customStyle').value || 'Not specified'}`, `Additional notes: ${el('customNotes').value || 'None'}`].join('\n'); const item = {product:{name:`Custom ${el('customType').value} request`},quantity:1,price:budget}; store.orders.push({id:`o${Date.now()}`,number:`KST-${String(store.orders.length + 1).padStart(4,'0')}`,customer:el('customName').value,contact:el('customContact').value,instructions:details,items:[item],total:budget,createdAt:new Date().toISOString(),status:'New'}); save(); el('customOrderForm').reset(); toast('Custom request sent. We will be in touch soon!'); });
document.addEventListener('change', event => { if (event.target.dataset.orderStatus) { const order = store.orders.find(item => item.id === event.target.dataset.orderStatus); order.status = event.target.value; save(); renderAdmin('orders'); toast('Order status updated'); } });
renderAll();
