const seedProducts = [
	{id:'p1',type:'cake',name:'Strawberry Cloud',description:'Vanilla sponge, fresh strawberries, and a soft whipped finish.',price:48,salePrice:39, sale:true,available:true,featured:true,isNew:false,image:'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=700&q=82'},
	{id:'p2',type:'cake',name:'Caramel Fig',description:'Brown sugar layers, salted caramel, and a little fig confit.',price:56,salePrice:null,sale:false,available:true,featured:true,isNew:true,image:'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?auto=format&fit=crop&w=700&q=82'},
	{id:'p3',type:'cake',name:'Citrus Olive Oil',description:'Bright lemon, orange zest, and a tender olive oil crumb.',price:42,salePrice:null,sale:false,available:true,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=700&q=82'},
	{id:'p4',type:'cupcake',name:'Rose Vanilla',description:'Silky vanilla buttercream finished with a rose petal.',price:5.5,salePrice:4.5,sale:true,available:true,featured:true,isNew:true,image:'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=700&q=82'},
	{id:'p5',type:'cupcake',name:'Dark Chocolate',description:'Deep cocoa cake with a glossy chocolate swirl.',price:5,salePrice:null,sale:false,available:true,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1599785209707-a456fc1337bb?auto=format&fit=crop&w=700&q=82'},
	{id:'p6',type:'cupcake',name:'Lemon Meringue',description:'Lemon curd centre, vanilla crumb, and toasted meringue.',price:5.5,salePrice:null,sale:false,available:false,featured:false,isNew:false,image:'https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=700&q=82'}
];
const store = { products: JSON.parse(localStorage.getItem('khloeProducts') || 'null') || seedProducts, orders: JSON.parse(localStorage.getItem('khloeOrders') || '[]'), whatsapp: localStorage.getItem('khloeWhatsapp') || '', basket: [] };
const money = value => 'K' + Number(value).toFixed(2);
const save = () => { localStorage.setItem('khloeProducts', JSON.stringify(store.products)); localStorage.setItem('khloeOrders', JSON.stringify(store.orders)); localStorage.setItem('khloeWhatsapp', store.whatsapp); };
const el = id => document.getElementById(id);
const show = id => el(id).classList.add('open');
const hide = id => el(id).classList.remove('open');
function toast(message) { const node = el('toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
function card(product) { const onSale = product.sale && product.salePrice && product.salePrice < product.price; const discount = onSale ? Math.round((1 - product.salePrice / product.price) * 100) : 0; return `<article class="product-card"><div class="product-image"><img src="${product.image || 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=82'}" alt="${product.name}">${onSale ? `<span class="badge">Sale -${discount}%</span>` : product.isNew ? '<span class="badge new">New</span>' : ''}</div><div class="product-body"><div class="product-top"><div class="product-title">${product.name}</div><span class="availability ${product.available ? '' : 'off'}">${product.available ? 'Available' : 'Sold out'}</span></div><p class="product-desc">${product.description}</p><div class="product-footer"><div class="price">${onSale ? `<span class="old-price">${money(product.price)}</span>${money(product.salePrice)}` : money(product.price)}</div><div class="card-actions">${product.available ? `<div class="quantity-control"><button type="button" data-quantity-minus="${product.id}" aria-label="Decrease quantity">-</button><input data-quantity="${product.id}" type="number" min="1" max="99" value="1" aria-label="Quantity for ${product.name}"><button type="button" data-quantity-plus="${product.id}" aria-label="Increase quantity">+</button></div>` : ''}<button class="mini-btn" data-add="${product.id}" ${product.available ? '' : 'disabled'}>${product.available ? 'Add to cart' : 'Unavailable'}</button></div></div></div></article>`; }
function renderGrid(id, products) { el(id).innerHTML = products.length ? products.map(card).join('') : '<div class="empty">No treats found here right now. Check back soon!</div>'; }
function renderAll() { const cakes = store.products.filter(p => p.type === 'cake'); const cupcakes = store.products.filter(p => p.type === 'cupcake'); renderGrid('featuredGrid', store.products.filter(p => p.featured).slice(0,3)); renderGrid('cakesGrid', filtered(cakes, document.querySelector('#cakes [data-search]'), document.querySelector('#cakes [data-filter]'))); renderGrid('cupcakesGrid', filtered(cupcakes, document.querySelector('#cupcakes [data-search]'), document.querySelector('#cupcakes [data-filter]'))); renderGrid('promotionsGrid', store.products.filter(p => p.sale && p.salePrice && p.salePrice < p.price)); el('cartCount').textContent = store.basket.reduce((sum,item) => sum + item.quantity, 0); }
function filtered(products, search, filter) { const term = search ? search.value.toLowerCase() : ''; return products.filter(p => (!term || `${p.name} ${p.description}`.toLowerCase().includes(term)) && (filter.value === 'all' || (filter.value === 'sale' ? p.sale : p.available))); }
function productUnitPrice(product) { return product.sale && product.salePrice < product.price ? product.salePrice : product.price; }
function renderBasket() { if (!store.basket.length) { el('basketItems').innerHTML = '<div class="empty">Your cart is waiting for something sweet.</div>'; return; } const total = store.basket.reduce((sum,item) => sum + item.quantity * productUnitPrice(item.product), 0); el('basketItems').innerHTML = `<div class="cart-items">${store.basket.map(item => `<div class="cart-item"><div><div class="cart-item-name">${item.product.name}</div><small style="color:var(--muted)">${money(productUnitPrice(item.product))} each</small></div><div class="quantity-control"><button type="button" data-cart-minus="${item.product.id}" aria-label="Decrease ${item.product.name}">-</button><input type="number" min="1" max="99" value="${item.quantity}" data-cart-quantity="${item.product.id}" aria-label="Quantity of ${item.product.name}"><button type="button" data-cart-plus="${item.product.id}" aria-label="Increase ${item.product.name}">+</button></div><div><strong class="cart-item-price">${money(item.quantity * productUnitPrice(item.product))}</strong><button type="button" class="cart-item-remove" data-cart-remove="${item.product.id}" aria-label="Remove ${item.product.name}">&times;</button></div></div>`).join('')}</div><div class="cart-summary"><span>Cart total</span><strong>${money(total)}</strong></div>`; }
function addToBasket(id, quantity = 1, trigger) { const product = store.products.find(p => p.id === id); const existing = store.basket.find(item => item.product.id === id); if (existing) existing.quantity += quantity; else store.basket.push({product,quantity}); renderAll(); if (trigger) { document.querySelectorAll(`[data-add="${id}"]`).forEach(button => { const productCard = button.closest('.product-card'); productCard.classList.remove('added'); requestAnimationFrame(() => productCard.classList.add('added')); }); } toast(`${quantity} ${product.name} ${quantity === 1 ? 'was' : 'were'} added to your cart`); }
function updateCartQuantity(id, quantity) { const item = store.basket.find(entry => entry.product.id === id); if (!item) return; item.quantity = Math.max(1, Math.min(99, quantity)); renderBasket(); renderAll(); }
function renderAdmin(view = 'products') { el('whatsappNumber').value = store.whatsapp; const area = el('adminContent'); if (view === 'orders') { const orders = [...store.orders].reverse(); el('orderCountLabel').textContent = orders.length ? `(${orders.length})` : ''; el('newOrderBadge').textContent = store.orders.filter(o => o.status === 'New').length ? '  • NEW ORDER' : ''; area.innerHTML = orders.length ? orders.map(order => `<div class="order-card"><div class="order-head"><strong>${order.number} &middot; ${order.customer}</strong><strong>${money(order.total)}</strong></div><div class="order-meta">${order.contact} &middot; ${new Date(order.createdAt).toLocaleString()}${order.instructions ? ` &middot; Note: ${order.instructions}` : ''}</div><div class="order-items">${order.items.map(item => `${item.quantity} &times; ${item.product.name} (${money(item.price)})`).join('<br>')}</div><select data-order-status="${order.id}">${['New','Confirmed','Preparing','Ready','Completed','Cancelled'].map(status => `<option ${status === order.status ? 'selected' : ''}>${status}</option>`).join('')}</select></div>`).join('') : '<div class="empty">No orders yet. New orders will appear here.</div>'; } else { area.innerHTML = `<div style="color:var(--muted);font-size:12px;margin-bottom:6px">${store.products.length} products in your public menu</div>` + store.products.map(p => `<div class="admin-product"><img src="${p.image}" alt=""><div class="admin-product-info"><strong>${p.name}</strong><small>${p.type} &middot; ${p.sale ? 'On sale' : 'Regular price'} &middot; ${p.available ? 'Available' : 'Unavailable'}</small></div><strong>${money(p.sale && p.salePrice < p.price ? p.salePrice : p.price)}</strong><div class="admin-product-actions"><button data-edit="${p.id}">Edit</button><button class="delete" data-delete="${p.id}">Delete</button></div></div>`).join(''); } }
function openWhatsApp(order) { const number = store.whatsapp.replace(/\D/g, ''); if (!number) { toast('Order saved. Add a WhatsApp number in the owner dashboard to send it.'); return; } const items = order.items.map(item => `${item.quantity} x ${item.product.name} - ${money(item.price * item.quantity)}`).join('\n'); const message = [`Hello khloe.s_sweet_treats, I would like to place an order.`,`Order: ${order.number}`,`Name: ${order.customer}`,`Contact: ${order.contact}`,`Items:\n${items}`,`Total: ${money(order.total)}`,order.instructions ? `Notes: ${order.instructions}` : ''].filter(Boolean).join('\n'); window.open(`https://wa.me/${number}?text=${encodeURIComponent(message)}`, '_blank'); }
function readImageFile(file) { return new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.onerror = reject; reader.readAsDataURL(file); }); }
function editProduct(product) { el('productModalTitle').textContent = product ? 'Edit product' : 'Add product'; el('productId').value = product?.id || ''; el('productType').value = product?.type || 'cake'; el('productName').value = product?.name || ''; el('productDescription').value = product?.description || ''; el('productPrice').value = product?.price || ''; el('productSalePrice').value = product?.salePrice || ''; el('productImage').value = ''; el('productImageCurrent').value = product?.image || ''; el('productSale').checked = !!product?.sale; el('productAvailable').checked = product ? product.available : true; el('productFeatured').checked = !!product?.featured; el('productNew').checked = !!product?.isNew; show('productModal'); }
document.addEventListener('click', event => { const add = event.target.closest('[data-add]'); if (add) { const quantity = Number(add.closest('.card-actions').querySelector('[data-quantity]').value) || 1; addToBasket(add.dataset.add, Math.max(1, Math.min(99, quantity)), add); } const productPlus = event.target.closest('[data-quantity-plus]'); if (productPlus) { const input = productPlus.closest('.quantity-control').querySelector('input'); input.value = Math.min(99, Number(input.value) + 1); } const productMinus = event.target.closest('[data-quantity-minus]'); if (productMinus) { const input = productMinus.closest('.quantity-control').querySelector('input'); input.value = Math.max(1, Number(input.value) - 1); } const cartPlus = event.target.closest('[data-cart-plus]'); if (cartPlus) { const item = store.basket.find(entry => entry.product.id === cartPlus.dataset.cartPlus); updateCartQuantity(cartPlus.dataset.cartPlus, item.quantity + 1); } const cartMinus = event.target.closest('[data-cart-minus]'); if (cartMinus) { const item = store.basket.find(entry => entry.product.id === cartMinus.dataset.cartMinus); updateCartQuantity(cartMinus.dataset.cartMinus, item.quantity - 1); } const cartRemove = event.target.closest('[data-cart-remove]'); if (cartRemove) { store.basket = store.basket.filter(item => item.product.id !== cartRemove.dataset.cartRemove); renderBasket(); renderAll(); } const edit = event.target.closest('[data-edit]'); if (edit) editProduct(store.products.find(p => p.id === edit.dataset.edit)); const remove = event.target.closest('[data-delete]'); if (remove && confirm('Remove this product from the menu?')) { store.products = store.products.filter(p => p.id !== remove.dataset.delete); save(); renderAll(); renderAdmin(); toast('Product removed'); } });
document.querySelectorAll('[data-close]').forEach(button => button.addEventListener('click', () => hide(button.dataset.close)));
document.querySelectorAll('[data-search],[data-filter]').forEach(control => control.addEventListener('input', renderAll));
document.addEventListener('change', event => { const cartQuantity = event.target.closest('[data-cart-quantity]'); if (cartQuantity) updateCartQuantity(cartQuantity.dataset.cartQuantity, Number(cartQuantity.value) || 1); if (event.target.dataset.orderStatus) { const order = store.orders.find(item => item.id === event.target.dataset.orderStatus); order.status = event.target.value; save(); renderAdmin('orders'); toast('Order status updated'); } });
el('cartBtn').addEventListener('click', () => { renderBasket(); show('orderModal'); });
el('menuBtn').addEventListener('click', () => el('navLinks').classList.toggle('open'));
const openLogin = () => show('loginModal'); el('adminBtn').addEventListener('click', openLogin); el('footerAdmin').addEventListener('click', openLogin);
el('loginForm').addEventListener('submit', event => { event.preventDefault(); if (el('adminPassword').value === 'khloe-admin') { hide('loginModal'); renderAdmin(); show('adminModal'); el('adminPassword').value = ''; } else toast('That password did not match.'); });
el('whatsappForm').addEventListener('submit', event => { event.preventDefault(); store.whatsapp = el('whatsappNumber').value.trim(); save(); toast(store.whatsapp ? 'WhatsApp number saved' : 'WhatsApp number cleared'); });
el('addProductBtn').addEventListener('click', () => editProduct()); el('ordersTabBtn').addEventListener('click', () => renderAdmin('orders'));
el('productForm').addEventListener('submit', async event => { event.preventDefault(); const imageFile = el('productImage').files[0]; const image = imageFile ? await readImageFile(imageFile) : (el('productImageCurrent').value || 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=700&q=82'); const id = el('productId').value || `p${Date.now()}`; const product = {id,type:el('productType').value,name:el('productName').value.trim(),description:el('productDescription').value.trim(),price:Number(el('productPrice').value),salePrice:el('productSalePrice').value ? Number(el('productSalePrice').value) : null,sale:el('productSale').checked,available:el('productAvailable').checked,featured:el('productFeatured').checked,isNew:el('productNew').checked,image}; const index = store.products.findIndex(p => p.id === id); if (index >= 0) store.products[index] = product; else store.products.push(product); save(); hide('productModal'); renderAll(); renderAdmin(); toast('Menu updated'); });
el('orderForm').addEventListener('submit', event => { event.preventDefault(); if (!store.basket.length) return toast('Add a treat before placing your order.'); const items = store.basket.map(item => ({product:item.product,quantity:item.quantity,price:productUnitPrice(item.product)})); const total = items.reduce((sum,item) => sum + item.quantity * item.price, 0); const order = {id:`o${Date.now()}`,number:`KST-${String(store.orders.length + 1).padStart(4,'0')}`,customer:el('customerName').value,contact:el('customerContact').value,instructions:el('instructions').value,items,total,createdAt:new Date().toISOString(),status:'New'}; store.orders.push(order); store.basket = []; save(); hide('orderModal'); el('orderForm').reset(); renderAll(); openWhatsApp(order); });
el('customOrderForm').addEventListener('submit', event => { event.preventDefault(); const budget = el('customBudget').value ? Number(el('customBudget').value) : 0; const details = [`Needed by: ${el('customDate').value}`, `Request type: ${el('customType').value}`, `Servings or quantity: ${el('customServings').value}`, `Flavours and fillings: ${el('customFlavours').value}`, `Colours, theme, and design: ${el('customStyle').value || 'Not specified'}`, `Additional notes: ${el('customNotes').value || 'None'}`].join('\n'); const item = {product:{name:`Custom ${el('customType').value} request`},quantity:1,price:budget}; const order = {id:`o${Date.now()}`,number:`KST-${String(store.orders.length + 1).padStart(4,'0')}`,customer:el('customName').value,contact:el('customContact').value,instructions:details,items:[item],total:budget,createdAt:new Date().toISOString(),status:'New'}; store.orders.push(order); save(); el('customOrderForm').reset(); openWhatsApp(order); });
renderAll();
